namespace: kube-monitoring
resources:
  - namespace.yaml
helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: kube-prometheus-stack 
    valuesFile: prometheus-stack-values.yaml
  - name: prometheus-blackbox-exporter # https://medium.com/@akashjoffical08/monitor-uptime-of-endpoints-in-k8s-using-blackbox-exporter-f80166a328e9
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: prometheus-blackbox-exporter
    valuesFile: blackbox-exporter-values.yaml
