---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`traefik.zelos.k8s.infra.erpf.de`) # Hostname to match
      kind: Rule
      services: # Service to redirect requests to
        - name: api@internal # Special service created by Traefik pod
          kind: TraefikService
      # middlewares:
      #   - name: traefik-basic-auth
  tls:
    secretName: traefik-erpf-de-tls
    
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-erpf-de-tls
spec:
  secretName: traefik-erpf-de-tls
  issuerRef:
    name: cloudflare-letsencrypt-prod
    kind: ClusterIssuer
  commonName: traefik.zelos.k8s.infra.erpf.de
  dnsNames:
  - "traefik.zelos.k8s.infra.erpf.de"