---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    email: content@jakoberpf.de
    privateKeySecretRef:
      name: cloudflare-staging-issuer
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            key: token
            name: cloudflare-api-credentials
          email: accounts@jakoberpf.de

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: content@jakoberpf.de
    privateKeySecretRef:
      name: cloudflare-prod-issuer-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            key: token
            name: cloudflare-api-credentials
          email: accounts@jakoberpf.de
